format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_memory}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_MEMORY_COMMON_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_memory, value: Asynchronous}
  - type: Boolean
    attributes: {id: DRV_MEMORY_COMMON_SYS_TIME_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_memory, value: 'false'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_memory}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: DRV_MEMORY_DEVICE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_0, value: NVMCTRL}
      - type: Comment
        attributes: {id: DRV_MEMORY_DEVICE_COMMENT}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: text}
            children:
            - {type: Value, value: '*** Configure Memory Device in NVMCTRL Configurations
                ***'}
      - type: Boolean
        attributes: {id: DRV_MEMORY_ERASE_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_0, value: 'true'}
      - type: Boolean
        attributes: {id: DRV_MEMORY_INTERRUPT_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_0, value: 'false'}
      - type: String
        attributes: {id: DRV_MEMORY_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_memory_0, value: DRV_NVMCTRL}
      - type: File
        attributes: {id: DRV_MEMORY_PLIB_HEADER}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: name}
            children:
            - {type: Value, value: drv_memory_nvmctrl.h}
      - type: File
        attributes: {id: DRV_MEMORY_PLIB_SOURCE}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: name}
            children:
            - {type: Value, value: drv_memory_nvmctrl.c}
      - type: Menu
        attributes: {id: DRV_MEMORY_RTOS_MENU}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'false'}
      - type: File
        attributes: {id: DRV_MEMORY_SYS_RTOS_TASK}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'false'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_memory_MEMORY_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: nvmctrl}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: NVMCTRL_MEMORY}
- type: ElementPosition
  attributes: {x: '172', y: '293', id: drv_memory}
