format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_usart}
children:
- type: Symbols
  children:
  - type: Combo
    attributes: {id: DRV_USART_COMMON_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_usart, value: Asynchronous}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_usart}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: DRV_USART_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usart_0, value: SERCOM3}
      - type: Integer
        attributes: {id: DRV_USART_RX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usart_0, value: '-1'}
      - type: Integer
        attributes: {id: DRV_USART_TX_DMA_CHANNEL}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usart_0, value: '-1'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_usart_UART_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: sercom3}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: SERCOM3_UART}
- type: ElementPosition
  attributes: {x: '168', y: '256', id: drv_usart}
