format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_sdmmc}
children:
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_sdmmc}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: DRV_SDMMC_CARD_DETECTION_METHOD}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdmmc_0, value: Use Polling}
      - type: Combo
        attributes: {id: DRV_SDMMC_CARD_DETECTION_METHODS_LIST2}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
      - type: String
        attributes: {id: DRV_SDMMC_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdmmc_0, value: SDMMC0}
      - type: Boolean
        attributes: {id: DRV_SDMMC_PLIB_SDCD_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdmmc_0, value: 'false'}
      - type: Boolean
        attributes: {id: DRV_SDMMC_PLIB_SDWP_ENABLE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdmmc_0, value: 'false'}
      - type: Integer
        attributes: {id: DRV_SDMMC_POLLING_INTERVAL}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: visible}
            children:
            - {type: Value, value: 'true'}
      - type: Combo
        attributes: {id: DRV_SDMMC_PROTOCOL_SUPPORT}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: readOnly}
            children:
            - {type: Value, value: 'false'}
      - type: Combo
        attributes: {id: DRV_SDMMC_TRANSFER_BUS_WIDTH}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_sdmmc_0, value: 4-bit}
      - type: Boolean
        attributes: {id: DRV_SDMMC_WP_CHECK_ENABLE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: readOnly}
            children:
            - {type: Value, value: 'false'}
    - type: Attachments
      children:
      - type: DirectDependency
        attributes: {id: drv_sdmmc_SDHC_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: sdmmc0}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: SDMMC0_SDHC}
- type: ElementPosition
  attributes: {x: '183', y: '315', id: drv_sdmmc}
