format_version: v1.0
type: GeneratorComponent
attributes: {id: usb_device_msd}
children:
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: usb_device_msd}
    children:
    - type: Symbols
      children:
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_BULK_IN_ENDPOINT_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_msd_0, value: '1'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_BULK_OUT_ENDPOINT_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_msd_0, value: '2'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_INTERFACE_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_msd_0, value: '0'}
      - type: Combo
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_MSD_LUN_MEDIA_TYPE_IDX0}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: MEDIA_TYPE_SD_CARD_MMC}
- type: ElementPosition
  attributes: {x: '321', y: '244', id: usb_device_msd}
