package:
  format-version: "1.0.0"
  name: "usb"
  type: "api"
  status: "production"
  required: false
  version: "v3.15.0-E1"

  dependencies:
    - name: "core"
      type: "package"
      version: "v3.14.0-E1"