package:
  format-version: "1.0.0"
  name: "usb"
  type: "api"
  status: "production"
  required: false
  version: "v3.11.0-E2"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.16.0"
    - name: "core"
      type: "package"
      version: "v3.12.0"

