package:
  format-version: "1.0.0"
  name: "usb"
  type: "api"
  status: "production"
  required: false
  version: "3.11.0-E1"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.15.0-E1"
    - name: "core"
      type: "package"
      version: "3.11.1"

