package:
  format-version: "1.0.0"
  name: "usb"
  type: "api"
  status: "production"
  required: false
  version: "v3.14.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "v3.19.1"
    - name: "core"
      type: "package"
      version: "v3.13.5"

