format_version: v1.0
type: UniqueComponent
attributes: {id: usb_device}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_CONFIG_DESCRPTR_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '41'}
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_ENDPOINTS_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '1'}
  - type: Boolean
    attributes: {id: CONFIG_USB_DEVICE_EVENT_ENABLE_SOF}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_FUNCTIONS_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '1'}
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_INTERFACES_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '1'}
- type: ElementPosition
  attributes: {x: '159', y: '275', id: usb_device}
