format_version: v1.0
type: UniqueComponent
attributes: {id: drv_usbhs_v1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: USB_DRIVER_RTOS_DELAY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '0', y: '305', id: drv_usbhs_v1}
