format_version: v1.0
type: UniqueComponent
attributes: {id: usb_host}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CONFIG_USB_HOST_TPL_ENTRY_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_host_msd, value: '1'}
  - type: Integer
    attributes: {id: USB_HOST_RTOS_DELAY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '170', y: '305', id: usb_host}
