configName: sam_e54_xpro_iar
folderName: sam_e54_xpro_iar.IAR
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAME54P20A
projectName: msd_basic_sam_e54_xpro_iar
settings:
  PackageFilter: bsp;core;csp;quick_docs;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.4.70\atdf\ATSAME54P20A.atdf
