format_version: v1.0
type: GeneratorComponent
attributes: {id: usb_device_hid}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_HID_QUEUE_DEPTH_COMBINED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device_hid, value: '2'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: usb_device_hid}
    children:
    - type: Symbols
      children:
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_INTERFACE_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_hid_0, value: '1'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_INT_IN_ENDPOINT_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_hid_0, value: '3'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_INT_OUT_ENDPOINT_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_hid_0, value: '4'}
      - type: Combo
        attributes: {id: CONFIG_USB_DEVICE_HID_REPORT_DESCRIPTOR_TYPE}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: Custom}
- type: ElementPosition
  attributes: {x: '303', y: '243', id: usb_device_hid}
