format_version: v1.0
type: UniqueComponent
attributes: {id: drv_usbhs_v1}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: USB_DEVICE_VBUS_SENSE_PIN_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: USB_VBUS_SENSE}
- type: ElementPosition
  attributes: {x: '0', y: '239', id: drv_usbhs_v1}
