format_version: v1.0
type: UniqueComponent
attributes: {id: usb_device}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_CONFIG_DESCRPTR_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '98'}
  - type: Boolean
    attributes: {id: CONFIG_USB_DEVICE_DESCRIPTOR_IAD_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: 'true'}
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_ENDPOINTS_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '5'}
  - type: Boolean
    attributes: {id: CONFIG_USB_DEVICE_EVENT_ENABLE_SOF}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_FUNCTIONS_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '2'}
  - type: Integer
    attributes: {id: CONFIG_USB_DEVICE_INTERFACES_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '3'}
  - type: Boolean
    attributes: {id: CONFIG_USB_DEVICE_MSD_DISK_IMAGE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: 'true'}
  - type: String
    attributes: {id: CONFIG_USB_DEVICE_PRODUCT_ID_IDX0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: '0x0057'}
  - type: Combo
    attributes: {id: CONFIG_USB_DEVICE_PRODUCT_ID_SELECTION_IDX0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: cdc_msd_basic_demo}
  - type: String
    attributes: {id: CONFIG_USB_DEVICE_PRODUCT_STRING_DESCRIPTOR}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: CDC + MSD Demo}
  - type: String
    attributes: {id: CONFIG_USB_DEVICE_SERIAL_NUMBER_STRING_DESCRIPTOR}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: CONFIG_USB_DEVICE_SERIAL_NUMBER_STRING_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: CONFIG_USB_DEVICE_SPEED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_usbhs_v1, value: High Speed}
  - type: Boolean
    attributes: {id: CONFIG_USB_DEVICE_USE_MSD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_device, value: 'true'}
  - type: File
    attributes: {id: USB_DEVICE_DISK_IMAGE_FILE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '166', y: '198', id: usb_device}
