format_version: v1.0
type: UniqueComponent
attributes: {id: pm}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: PM_PLCFG_PLSEL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pm, value: '1'}
  - type: KeyValueSet
    attributes: {id: PM_STDBYCFG_VREGSMOD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '169', y: '95', id: pm}
