configName: sam_9x60_ek_iar
folderName: ''
format_version: v1.0
frameworkPath: C:\Repos\H3
processor: SAM9X60
projectName: printer_basic_sam_9x60_ek_iar
settings:
  PackageFilter: audio;bsp;core;csp;csp_apps_pic32cm_le00_ls00;csp_apps_sam_l21;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\1.4.40\atdf\SAM9X60.atdf
