format_version: v1.0
type: GeneratorComponent
attributes: {id: usb_device_printer}
children:
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: usb_device_printer}
    children:
    - type: Symbols
      children:
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_BULK_OUT_ENDPOINT_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_printer_0, value: '1'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTION_INTERFACE_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_printer_0, value: '0'}
- type: ElementPosition
  attributes: {x: '320', y: '306', id: usb_device_printer}
