configName: pic32mz_ef_sk
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MZ2048EFH144
projectName: ''
settings:
  PackageFilter: bsp;core;csp;ethercat;usb;validation;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.57\atdf\PIC32MZ2048EFH144.atdf
