configName: sam_v71_xult_freertos
folderName: sam_v71_xult_freertos.X
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMV71Q21B
projectName: cdc_com_port_dual_sam_v71_xult_freertos
settings:
  PackageFilter: bsp;core;csp;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMV71_DFP\4.3.66\samv71b\atdf\ATSAMV71Q21B.atdf
