format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_SAM_E70_Xplained_Ultra, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '150', y: '44', id: BSP_SAM_E70_Xplained_Ultra}
