format_version: v1.0
type: UniqueComponent
attributes: {id: sdmmc0}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SDCARD_EMMCEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_sdmmc_0, value: 'false'}
  - type: Comment
    attributes: {id: SDMMC0_CLK_ENABLE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Comment
    attributes: {id: SDMMC0_INTERRUPT_ENABLE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: SDMMC_BASECLK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sdmmc0, value: '300000000'}
  - type: Comment
    attributes: {id: SDMMC_BASE_CLOCK_SOURCE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: SDMMC_HCLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sdmmc0, value: '200000000'}
  - type: Integer
    attributes: {id: SDMMC_MULTCLK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sdmmc0, value: '600000000'}
  - type: Comment
    attributes: {id: SDMMC_MULT_CLOCK_SOURCE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: SDMMC0_SDHC}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_sdmmc_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_sdmmc_SDHC_dependency}
- type: ElementPosition
  attributes: {x: '0', y: '419', id: sdmmc0}
