configName: sam_e70_xult_freertos
folderName: sam_e70_xult_freertos.X
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAME70Q21B
projectName: cdc_com_port_dual_sam_e70_xult_freertos
settings:
  PackageFilter: bsp;core;csp;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME70_DFP\4.3.67\same70b\atdf\ATSAME70Q21B.atdf
