format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_PIC32MK_GP_Development_Kit, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '21', y: '60', id: BSP_PIC32MK_GP_Development_Kit}
