format_version: v1.0
type: GeneratorComponent
attributes: {id: usb_device}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: CONFIG_USB_DEVICE_EVENT_ENABLE_SOF}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: usb_device}
    children:
    - type: Symbols
      children:
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_CONFIG_DESCRPTR_SIZE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: '67'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_ENDPOINTS_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: '2'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTIONS_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: '1'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_INTERFACES_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: '2'}
      - type: Boolean
        attributes: {id: CONFIG_USB_DEVICE_MSD_DISK_IMAGE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: 'false'}
      - type: String
        attributes: {id: CONFIG_USB_DEVICE_PRODUCT_ID_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: '0x000A'}
      - type: Combo
        attributes: {id: CONFIG_USB_DEVICE_PRODUCT_ID_SELECTION_IDX0}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: cdc_com_port_single_demo}
      - type: String
        attributes: {id: CONFIG_USB_DEVICE_PRODUCT_STRING_DESCRIPTOR}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: Simple CDC Device Demo}
      - type: String
        attributes: {id: USB_DEVICE_INDEX}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_0, value: DRV_USBFS_INDEX_0}
    - type: Attachments
      children:
      - type: DirectCapability
        attributes: {id: USB Device}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: usb_device_cdc_0}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: usb_device_dependency}
      - type: DirectDependency
        attributes: {id: usb_driver_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: drv_usbfs_index_0}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: DRV_USB}
  - type: InstanceComponent
    attributes: {instance: '1', id: usb_device}
    children:
    - type: Symbols
      children:
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_CONFIG_DESCRPTR_SIZE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_1, value: '67'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_ENDPOINTS_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_1, value: '2'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_FUNCTIONS_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_1, value: '1'}
      - type: Integer
        attributes: {id: CONFIG_USB_DEVICE_INTERFACES_NUMBER}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_1, value: '2'}
      - type: Boolean
        attributes: {id: CONFIG_USB_DEVICE_MSD_DISK_IMAGE}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_1, value: 'false'}
      - type: String
        attributes: {id: CONFIG_USB_DEVICE_PRODUCT_ID_IDX0}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_1, value: '0x000A'}
      - type: Combo
        attributes: {id: CONFIG_USB_DEVICE_PRODUCT_ID_SELECTION_IDX0}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: cdc_com_port_single_demo}
      - type: String
        attributes: {id: CONFIG_USB_DEVICE_PRODUCT_STRING_DESCRIPTOR}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_1, value: Simple CDC Device Demo}
      - type: String
        attributes: {id: USB_DEVICE_INDEX}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: usb_device_1, value: DRV_USBFS_INDEX_1}
    - type: Attachments
      children:
      - type: DirectCapability
        attributes: {id: USB Device}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: usb_device_cdc_1}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: usb_device_dependency}
      - type: DirectDependency
        attributes: {id: usb_driver_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: drv_usbfs_index_1}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: DRV_USB}
- type: ElementPosition
  attributes: {x: '254', y: '152', id: usb_device}
