format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_SAM_E70_Xplained_Ultra, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '138', y: '29', id: BSP_SAM_E70_Xplained_Ultra}
