format_version: v1.0
type: UniqueComponent
attributes: {id: usb_host_hid}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CONFIG_USB_HID_TOTAL_USAGE_DRIVER_INSTANCES}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_host_hid, value: '3'}
  - type: Integer
    attributes: {id: CONFIG_USB_HOST_HID_MOUSE_BUTTONS_NUMBER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Boolean
    attributes: {id: CONFIG_USB_HOST_USE_MOUSE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: CONFIG_USB_HOST_USE_MOUSE_SAVE_STATUS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_host_hid, value: 'true'}
  - type: File
    attributes: {id: USB_HOST_HID_MOUSE_HEADER}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: USB_HOST_HID_MOUSE_HEADER_LOCAL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: USB_HOST_HID_MOUSE_SOURCE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
- type: ElementPosition
  attributes: {x: '293', y: '342', id: usb_host_hid}
