format_version: v1.0
type: UniqueComponent
attributes: {id: BSP_SAM_V71_Xplained_Ultra, bsp: 'true'}
children:
- type: ElementPosition
  attributes: {x: '149', y: '45', id: BSP_SAM_V71_Xplained_Ultra}
