configName: sam_d21_xpro_iar
folderName: ''
format_version: v1.0
frameworkPath: C:\Repos\H3
processor: ATSAMD21J18A
projectName: msd_basic_sam_d21_xpro_iar
settings:
  PackageFilter: bsp;core;csp;quick_docs;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD21_DFP\3.4.104\samd21a\atdf\ATSAMD21J18A.atdf
