format_version: v1.0
type: UniqueComponent
attributes: {id: pit}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: CALLBACK_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pit, value: PIT_TimerCallbackSet}
  - type: String
    attributes: {id: COMPARE_SET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pit, value: PIT_TimerCompareSet}
  - type: String
    attributes: {id: COUNTER_GET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pit, value: PIT_TimerCounterGet}
  - type: Boolean
    attributes: {id: ENABLE_COUNTER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: 'false'}
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: FREQUENCY_GET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pit, value: PIT_TimerFrequencyGet}
  - type: String
    attributes: {id: IRQ_ENUM_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pit, value: PIT_IRQn}
  - type: String
    attributes: {id: PERIOD_SET_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pit, value: PIT_TimerPeriodSet}
  - type: Integer
    attributes: {id: PERIOD_TICKS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pit, value: '12500'}
  - type: String
    attributes: {id: TIMER_START_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pit, value: PIT_TimerStart}
  - type: String
    attributes: {id: TIMER_STOP_API_NAME}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pit, value: 'PIT_TimerStop '}
- type: ElementPosition
  attributes: {x: '166', y: '106', id: pit}
