format_version: v1.0
type: UniqueComponent
attributes: {id: usb_host}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CONFIG_USB_HOST_ATTACHED_CONTROLLERS_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_host, value: '1'}
  - type: Integer
    attributes: {id: CONFIG_USB_HOST_TPL_ENTRY_NUMBER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: usb_host, value: '1'}
- type: Attachments
  children:
  - type: MultiCapability
    attributes: {id: usb_driver_dependency}
    children:
    - type: TargetAttachments
      children:
      - type: TargetAttachment
        attributes: {targetComponentID: drv_usbfs_index_0, targetAttachmentID: DRV_USB}
- type: ElementPosition
  attributes: {x: '263', y: '143', id: usb_host}
