format_version: v1.0
type: UniqueComponent
attributes: {id: nvmctrl}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: NVM_RWS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
- type: ElementPosition
  attributes: {x: '196', y: '67', id: nvmctrl}
