configName: sam_a5d2_xult_iar_freertos
folderName: ''
format_version: v1.0
frameworkPath: C:\jcb\usb\repo\H3
processor: ATSAMA5D27
projectName: hub_msd_sam_a5d2_xult_iar_freertos
settings:
  PackageFilter: bootloader;bootloader_apps_usb;bsp;core;core_apps_pic32mx;core_apps_pic32mz_ef;core_apps_pic32mz_w1;core_apps_sam_d21_da1;core_apps_sam_d5x_e5x;crypto;csp;net;quick_docs;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMA5D2_DFP\1.5.42\atdf\ATSAMA5D27.atdf
