format_version: v1.0
type: UniqueComponent
attributes: {id: peripheral_usb_2}
children:
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: USB_2}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_usbfs_index_1}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: usb_peripheral_dependency}
- type: ElementPosition
  attributes: {x: '0', y: '247', id: peripheral_usb_2}
