format_version: v1.0
type: GeneratorComponent
attributes: {id: drv_usbfs_index}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DRV_USBFS_MULTI_DEVICE_SUPPORT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_usbfs_index, value: 'false'}
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: DRV_USBFS_MULTI_HOST_SUPPORT}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drv_usbfs_index, value: 'true'}
      - type: User
        attributes: {value: 'true'}
- type: Instances
  children:
  - type: InstanceComponent
    attributes: {instance: '0', id: drv_usbfs_index}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: DRV_USB_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usbfs_index_0, value: PERIPHERAL_USB_1}
      - type: File
        attributes: {id: USB_HOST_CONTROLLER_ENTRY_FILE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: Combo
        attributes: {id: USB_OPERATION_MODE}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: Host}
    - type: Attachments
      children:
      - type: DirectCapability
        attributes: {id: DRV_USB}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: usb_host}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: usb_driver_dependency}
      - type: DirectDependency
        attributes: {id: usb_peripheral_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: peripheral_usb_1}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: USB_1}
  - type: InstanceComponent
    attributes: {instance: '1', id: drv_usbfs_index}
    children:
    - type: Symbols
      children:
      - type: String
        attributes: {id: DRV_USB_PLIB}
        children:
        - type: Values
          children:
          - type: Dynamic
            attributes: {id: drv_usbfs_index_1, value: PERIPHERAL_USB_2}
      - type: File
        attributes: {id: USB_HOST_CONTROLLER_ENTRY_FILE}
        children:
        - type: Attributes
          children:
          - type: Boolean
            attributes: {id: enabled}
            children:
            - {type: Value, value: 'true'}
      - type: Combo
        attributes: {id: USB_OPERATION_MODE}
        children:
        - type: Values
          children:
          - type: User
            attributes: {value: Host}
    - type: Attachments
      children:
      - type: DirectCapability
        attributes: {id: DRV_USB}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: usb_host}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: usb_driver_dependency}
      - type: DirectDependency
        attributes: {id: usb_peripheral_dependency}
        children:
        - type: Attributes
          children:
          - type: String
            attributes: {id: targetComponentID}
            children:
            - {type: Value, value: peripheral_usb_2}
          - type: String
            attributes: {id: targetAttachmentID}
            children:
            - {type: Value, value: USB_2}
- type: ElementPosition
  attributes: {x: '120', y: '92', id: drv_usbfs_index}
